# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 07:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage('media/images'), upload_to=b'')),
            ],
        ),
    ]
